# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.2.3
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

# Install base and build packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    default-mysql-client \
    default-libmysqlclient-dev \
    git \
    libvips \
    libyaml-dev \
    pkg-config \
    curl && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application files
COPY . .

# Entrypoint script handles PID cleanup
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
